name: cnc-combined-arms
base: core22
version: '1.04'
summary: "Command & Conquer - Combined Arms"
description: Combined Arms is a standalone mod of Command & Conquer Red Alert.
grade: stable
confinement: strict
compression: lzo

apps:
  cnc-combined-arms:
    extensions: [gnome]
    command: usr/bin/openra-ca
    common-id: openra-ca.desktop
    desktop: usr/share/applications/openra-ca.desktop
    plugs:
      - audio-playback
      - avahi-control
      - avahi-observe
      - desktop
      - mount-observe
      - network
      - network-bind
      - opengl
      - removable-media
      - wayland
      - x11

architectures:
  - build-on: [amd64]
    build-for: [amd64]

parts:
  install-dotnet:
    plugin: nil
    build-packages:
      - curl
    override-pull: |
      curl -LO https://dot.net/v1/dotnet-install.sh
      chmod +x dotnet-install.sh
      ./dotnet-install.sh --channel LTS

  cnc-combined-arms:
    after: [install-dotnet]
    plugin: dump
    build-packages:
      - sed
    source: https://github.com/Inq8/CAmod/releases/download/1.04/CombinedArms-1.04-x86_64.AppImage
    source-type: file
    override-build: |
      chmod +x $SNAPCRAFT_PART_SRC/CombinedArms-1.04-x86_64.AppImage
      $SNAPCRAFT_PART_SRC/CombinedArms-1.04-x86_64.AppImage --appimage-extract
      rm -rf $SNAPCRAFT_PART_INSTALL/*
      mv squashfs-root/* $SNAPCRAFT_PART_INSTALL/

      sed -i -Ee 's|^Icon=(.*)$|Icon=/usr/share/icons/hicolor/1024x1024/apps/\1.png|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/openra-ca.desktop
