name: cnc-combined-arms
base: core22
version: '1.04'
summary: "OpenRA - Combined Arms"
description: | 
  What started out as a simple fusion of the Westwood original _Tiberian Dawn_ and _Red Alert_ games, the project evolved by incorporating a plethora of new units, gameplay mechanics, and additional features.
  
  **The game includes five main factions:**
  * Allies
  * Soviets
  * GDI
  * Nod
  * Scrin
  
  
  Each of which, having four unique sub-factions with their own units, powers and upgrades.
  
  Drawing from the extensive C&C franchise, the game incorporates units, structures, powers, and upgrades recreated in the _Tiberian Dawn_/_Red Alert_ art style.
  
  A comprehensive campaign, currently encompassing **34 missions**, unfolds a narrative detailing the interwoven universes and timelines.
  
  The experience extends further with Skirmish AI difficulties ranging from Easy to **Brutal**, providing a challenge even for highly skilled players.
  
  Over **450 maps** are included, including many competitive maps used in the base RA mod of OpenRA.
  
  Balancing for competitive play has been a major focus. 1v1 ladder servers are hosted, linked to player rankings and statistics, with the hope to build a competitive community moving forward.
  
  **About the Snap**
  
  This is a Snap package for _OpenRA - Combined Arms_, a modern remake of _Command & Conquer_ games powered by the _OpenRA engine_.
  
  This snap was created to provide a safer and more secure way to enjoy _OpenRA - Combined Arms_. 
  By confining the game within a _sandboxed_ environment, the snap limits its access to system resources, ensuring that it can run safely without interfering with your operating system or accessing sensitive data. 
  This approach not only enhances security but also makes the game easier to install and run across different Linux distributions, leveraging the convenience of Snap's universal packaging format.
  
  
  **Credits**
  
  * Inq8 and CAMod contributors
  * OpenRA Dev team (& Westwood) 

grade: stable
confinement: strict
compression: lzo

apps:
  cnc-combined-arms:
    extensions: [gnome]
    command: usr/bin/openra-ca
    common-id: openra-ca.desktop
    desktop: usr/share/applications/openra-ca.desktop
    plugs:
      - audio-playback
      - avahi-control
      - avahi-observe
      - desktop
      - mount-observe
      - network
      - network-bind
      - opengl
      - removable-media
      - wayland
      - x11

architectures:
  - build-on: [amd64]
    build-for: [amd64]

parts:
  install-dotnet:
    plugin: nil
    build-packages:
      - curl
    override-pull: |
      curl -LO https://dot.net/v1/dotnet-install.sh
      chmod +x dotnet-install.sh
      ./dotnet-install.sh --channel LTS

  cnc-combined-arms:
    after: [install-dotnet]
    plugin: dump
    build-packages:
      - sed
    source: https://github.com/Inq8/CAmod/releases/download/1.04/CombinedArms-1.04-x86_64.AppImage
    source-type: file
    override-build: |
      chmod +x $SNAPCRAFT_PART_SRC/CombinedArms-1.04-x86_64.AppImage
      $SNAPCRAFT_PART_SRC/CombinedArms-1.04-x86_64.AppImage --appimage-extract
      rm -rf $SNAPCRAFT_PART_INSTALL/*
      mv squashfs-root/* $SNAPCRAFT_PART_INSTALL/

      sed -i -Ee 's|^Icon=(.*)$|Icon=/usr/share/icons/hicolor/1024x1024/apps/\1.png|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/openra-ca.desktop
